Updating the public sourcefuse eks module
sourcefuse/terraform-aws-arc-eks pull request #91
Opened 2024-04-05 04:13 UTC by divyaperumal-sf

Why:
* Need to update the eks module to point to latest cloudposse module.
* Need to remove unwanted reference from the example and reference

How:
* Updated cloudposse version and updated the variables.

issue: #75

2024-04-09 11:10 UTC, vijay-stephen requested changes

2024-04-09 11:10 UTC, vijay-stephen commented on variables.tf
> +# variable "map_additional_iam_users" {
is this variable not being used ?

2024-04-09 11:10 UTC, vijay-stephen commented on variables.tf
>  ## workers
if not used, remove it

2024-04-09 11:10 UTC, vijay-stephen commented on locals.tf
> -  map_additional_iam_roles = concat(var.map_additional_iam_roles, [
how do we add additional roles ?

2024-04-09 11:11 UTC, vijay-stephen commented
@divyaperumal-sf please run the pre-commit

2024-04-09 11:14 UTC, vijay-stephen commented on locals.tf
> -  map_additional_iam_roles = concat(var.map_additional_iam_roles, [
@divyaperumal-sf Please test the updates and paste the screenshots

2024-04-22 18:59 UTC, mayank0202 commented
@divyaperumal-sf  Whats the status of this PR?

2025-05-15 07:14 UTC, closed without merging